name: Upload App to S3

on:
  # Set your workflow to run on push events to the develop and all feature branches
  push:
    branches:
      - develop
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: change directory & Deploy static site to S3 bucket
      run:  cd /home/runner/work/elitelabtools/elitelabtools/app

    - name: run s3 sync  
      run:  aws s3 cp app/ s3://${{ secrets.S3_BUCKET_NAME }}
